spring:
    datasource:
#        url: jdbc:h2:mem:kwk;MODE=mysql;DB_CLOSE_DELAY=-1
        url: jdbc:mysql://localhost:3306/kwk
        #Only for MYSQL
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
    h2:
        console:
            enable: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    jackson.serialization.fail-on-empty-beans: false